pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = '301276846759'
        ECR_REPO_NAME = 'fastapi-app'
        ECR_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}"
        IMAGE_TAG = "${BUILD_NUMBER}"
        SERVICE_NAME = 'fastapi-service'
        SWARM_MANAGER = 'ubuntu@10.0.1.36'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build --progress=plain \
                -t ${ECR_REPO_NAME}:${IMAGE_TAG} \
                fastapi-app
                '''
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin ${ECR_REPO}
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                docker tag ${ECR_REPO_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                docker push ${ECR_REPO}:${IMAGE_TAG}
                '''
            }
        }

        stage('Deploy to Swarm') {
            steps {
                sh '''
                ssh -o StrictHostKeyChecking=no ${SWARM_MANAGER} "
                docker service update \
                  --image ${ECR_REPO}:${IMAGE_TAG} \
                  ${SERVICE_NAME}
                "
                '''
            }
        }
    }
}